export default favoriteLeagues = [
  {
    league_id: 787,
    name: "Super League",
    type: "League",
    country: "Greece",
    country_code: "GR",
    season: 2019,
    season_start: "2019-08-24",
    season_end: "2020-02-29",
    logo: "https://media.api-football.com/leagues/108.png",
    flag: "https://media.api-football.com/flags/gr.svg",
    standings: 1,
    is_current: 1
  },
  {
    league_id: 775,
    name: "Primera Division",
    type: "League",
    country: "Spain",
    country_code: "ES",
    season: 2019,
    season_start: "2019-08-16",
    season_end: "2020-05-23",
    logo: "https://media.api-football.com/leagues/87.png",
    flag: "https://media.api-football.com/flags/es.svg",
    standings: 1,
    is_current: 1
  },
  {
    league_id: 754,
    name: "Bundesliga 1",
    type: "League",
    country: "Germany",
    country_code: "DE",
    season: 2019,
    season_start: "2019-08-16",
    season_end: "2020-05-16",
    logo: "https://media.api-football.com/leagues/8.png",
    flag: "https://media.api-football.com/flags/de.svg",
    standings: 1,
    is_current: 1
  },
  {
    league_id: 524,
    name: "Premier League",
    type: "League",
    country: "England",
    country_code: "GB",
    season: 2019,
    season_start: "2019-08-09",
    season_end: "2020-05-17",
    logo: "https://media.api-football.com/leagues/2.png",
    flag: "https://media.api-football.com/flags/gb.svg",
    standings: 1,
    is_current: 1
  },
  {
    league_id: 525,
    name: "Ligue 1",
    type: "League",
    country: "France",
    country_code: "FR",
    season: 2019,
    season_start: "2019-08-09",
    season_end: "2020-05-22",
    logo: "https://media.api-football.com/leagues/4.svg",
    flag: "https://media.api-football.com/flags/fr.svg",
    standings: 1,
    is_current: 1
  },
  {
    league_id: 891,
    name: "Serie A",
    type: "League",
    country: "Italy",
    country_code: "IT",
    season: 2019,
    season_start: "2019-08-24",
    season_end: "2020-05-23",
    logo: "https://media.api-football.com/leagues/94.png",
    flag: "https://media.api-football.com/flags/it.svg",
    standings: 1,
    is_current: 1
  },
  {
    league_id: 766,
    name: "Primeira Liga",
    type: "League",
    country: "Portugal",
    country_code: "PT",
    season: 2019,
    season_start: "2019-08-09",
    season_end: "2020-05-17",
    logo: "https://media.api-football.com/leagues/11.png",
    flag: "https://media.api-football.com/flags/pt.svg",
    standings: 1,
    is_current: 1
  },
  {
    league_id: 530,
    name: "Champions League",
    type: "Cup",
    country: "World",
    country_code: null,
    season: 2019,
    season_start: "2019-06-25",
    season_end: "2019-12-11",
    logo: "https://media.api-football.com/leagues/132.png",
    flag: null,
    standings: 0,
    is_current: 1
  },
  {
    league_id: 514,
    name: "Europa League",
    type: "Cup",
    country: "World",
    country_code: null,
    season: 2019,
    season_start: "2019-06-27",
    season_end: "2019-12-12",
    logo: "https://media.api-football.com/leagues/137.png",
    flag: null,
    standings: 1,
    is_current: 1
  }
];
